### PR TITLE
Rename/simplify package

### PR DESCRIPTION
**Pull request by KevinEtienne**
`from pgcrypto_fields import fields` could be `from pgcrypto import fields`

### CODE REVIEW

**Comment by KevinEtienne** [comment]
@meshy can you review/merge please?

**Comment by meshy** [comment]
This looks fine to me as long as you're aware that there's another python package with the same namespace?

**Comment by KevinEtienne** [comment]
I'm happy with this as they will never collide.

**Comment by meshy** [comment]
:+1:

**Pull request merged**
